# Cloud Build configuration for Codex Gateway
# This pipeline builds the Docker image and deploys to Cloud Run
#
# Trigger: Push to main/master branch or manual trigger
# Output: Docker image in Artifact Registry + Cloud Run deployment

steps:
  # Step 1: Build Docker image with BuildKit cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - '-c'
      - |
        set -e

        # Criar builder buildx
        docker buildx create --use --name=codex-builder --driver=docker-container 2>/dev/null || \
        docker buildx use codex-builder 2>/dev/null || \
        docker buildx create --use --name=codex-builder --driver=docker-container

        cd codex-rs

        # Build com cache eficiente e push
        docker buildx build \
          --platform linux/amd64 \
          --cache-from type=registry,ref=us-central1-docker.pkg.dev/$PROJECT_ID/codex-wrapper/wrapper:buildcache \
          --cache-to type=registry,ref=us-central1-docker.pkg.dev/$PROJECT_ID/codex-wrapper/wrapper:buildcache,mode=max \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/codex-wrapper/wrapper:$COMMIT_SHA \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/codex-wrapper/wrapper:latest \
          -f Dockerfile \
          --push \
          .
    timeout: '1800s' # 30 minutes for Rust build

  # Step 2: Deploy to Cloud Run (imagens já foram pushed no buildx)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'wrapper'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/codex-wrapper/wrapper:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--service-account=467992722695-compute@developer.gserviceaccount.com'
      # Preserve existing configuration
      - '--max-instances=20'
      - '--cpu=2'
      - '--memory=4Gi'
      - '--timeout=300s'
      - '--concurrency=80'
      - '--port=8080'
      # Environment variables
      - '--set-env-vars=RUST_LOG=info,codex_gateway=debug'
      - '--set-env-vars=PORT=8080'
      - '--set-env-vars=GATEWAY_HOST=0.0.0.0'
      - '--set-env-vars=REQUEST_TIMEOUT_SECS=300'
      - '--set-env-vars=GATEWAY_BODY_LIMIT_DEFAULT=2097152'
      - '--set-env-vars=GATEWAY_BODY_LIMIT_JSONRPC=1048576'
      - '--set-env-vars=GATEWAY_BODY_LIMIT_WEBHOOK=10485760'
      - '--set-env-vars=GATEWAY_BODY_LIMIT_WEBSOCKET=1048576'
      - '--set-env-vars=GATEWAY_BODY_LIMITS_ENABLED=true'
      - '--set-env-vars=GATEWAY_WEBSOCKET_MAX_CONNECTIONS=5000'
      - '--set-env-vars=GCS_BUCKET_NAME=elaihub-prod-codex-artifacts'
      - '--set-env-vars=FIRESTORE_PROJECT_ID=elaihub-prod'
      - '--set-env-vars=FIRESTORE_DATABASE_ID=(default)'
      # Secrets from Secret Manager
      - '--set-secrets=GATEWAY_API_KEY=gateway-api-key:latest'
      - '--set-secrets=ANTHROPIC_API_KEY=anthropic-api-key:latest'
      - '--set-secrets=OPENAI_API_KEY=openai-api-key:latest'
      - '--set-secrets=PIPEDRIVE_API_TOKEN=pipedrive-api-token:latest'
      # Allow unauthenticated (if public API) - adjust as needed
      - '--allow-unauthenticated'
    waitFor: ['build-image']  # Buildx já fez push

  # Step 3: Verify deployment health
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'verify-deployment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the service URL
        SVC_URL=$$(gcloud run services describe wrapper \
          --region=us-central1 \
          --format='value(status.url)')

        echo "Service URL: $$SVC_URL"

        # Wait for service to be ready
        sleep 10

        # Health check
        HTTP_STATUS=$$(curl -s -o /dev/null -w "%{http_code}" "$$SVC_URL/health")

        if [ "$$HTTP_STATUS" -eq 200 ]; then
          echo "✅ Health check passed (HTTP $$HTTP_STATUS)"
          exit 0
        else
          echo "❌ Health check failed (HTTP $$HTTP_STATUS)"
          exit 1
        fi
    waitFor: ['deploy-cloud-run']

# Images to be pushed to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/codex-wrapper/wrapper:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/codex-wrapper/wrapper:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/codex-wrapper/wrapper:buildcache'

# Build options
options:
  # Use high CPU machine for faster Rust builds
  machineType: 'E2_HIGHCPU_32'

  # Larger disk for cache
  diskSizeGb: 200

  # Use Cloud Build's Docker cache
  substitutionOption: 'ALLOW_LOOSE'

  # Logging
  logging: CLOUD_LOGGING_ONLY

# Substitutions (can be overridden at build time)
substitutions:
  _DEPLOY_REGION: 'us-central1'
  _SERVICE_NAME: 'wrapper'

# Tags for organizing builds
tags:
  - 'codex-gateway'
  - 'cloud-run'
  - 'rust'

# Timeout for entire build (40 minutes for Rust compilation)
timeout: '2400s'
